from datetime import date


def generate_markdown_report(volunteer_name: str, transcript: str, results: dict) -> str:
    signals = results.get("signals") or []
    mi = results.get("mi_results") or {}
    coaching = results.get("coaching") or {}
    score = coaching.get("score", 0) if isinstance(coaching, dict) else 0
    mi_score = mi.get("overall_mi_score", 0) if isinstance(mi, dict) else 0
    today = date.today().strftime("%B %d, %Y")

    lines = []

    lines.append(f"# CrisisLens Analysis Report")
    lines.append(f"")
    lines.append(f"**Volunteer:** {volunteer_name}  ")
    lines.append(f"**Date:** {today}  ")
    lines.append(f"**Overall Score:** {score}/100  ")
    lines.append(f"**MI Score:** {mi_score}/100  ")
    lines.append(f"**Risk Signals Detected:** {len(signals)}  ")
    lines.append(f"")
    lines.append("---")
    lines.append("")

    # Risk signals
    lines.append("## Risk Signals")
    lines.append("")
    if not signals:
        lines.append("No risk signals detected.")
    else:
        for level in ["HIGH", "MEDIUM", "LOW"]:
            subset = [s for s in signals if s.get("confidence") == level]
            if subset:
                lines.append(f"### {level.capitalize()} Confidence")
                lines.append("")
                for s in subset:
                    lines.append(f"**Exchange {s.get('exchange_number')} · {s.get('category', '')}**")
                    lines.append(f"> \"{s.get('caller_text', '')}\"")
                    lines.append(f"")
                    lines.append(f"*Reasoning:* {s.get('reasoning', '')}")
                    if s.get("confidence_reasoning"):
                        lines.append(f"*Confidence:* {s.get('confidence_reasoning', '')}")
                    lines.append("")
    lines.append("---")
    lines.append("")

    # MI assessment
    lines.append("## Motivational Interviewing Assessment")
    lines.append("")
    if isinstance(mi, dict):
        if mi.get("strengths"):
            lines.append("### Strengths")
            for s in mi.get("strengths", []):
                lines.append(f"- ✓ {s}")
            lines.append("")
        if mi.get("gaps"):
            lines.append("### Gaps")
            for g in mi.get("gaps", []):
                lines.append(f"- ⚠ {g}")
            lines.append("")
        if mi.get("critical_misses"):
            lines.append("### Critical Misses")
            for cm in mi.get("critical_misses", []):
                lines.append(f"- ✕ {cm}")
            lines.append("")
    lines.append("---")
    lines.append("")

    # Coaching feedback
    lines.append("## Coaching Feedback")
    lines.append("")
    if isinstance(coaching, dict):
        if coaching.get("summary"):
            lines.append(f"**Supervisor Summary:** {coaching.get('summary', '')}")
            lines.append("")
        for pf in coaching.get("priority_feedback", []):
            lines.append(f"### Exchange {pf.get('exchange', '')} — {pf.get('issue', '')}")
            lines.append(f"")
            lines.append(f"**Caller said:** \"{pf.get('caller_signal', '')}\"  ")
            lines.append(f"**Volunteer said:** \"{pf.get('volunteer_response', '')}\"  ")
            lines.append(f"")
            lines.append(f"**Recommended response:**")
            lines.append(f"> {pf.get('recommended_response', '')}")
            lines.append("")
        if coaching.get("mi_feedback"):
            lines.append(f"**MI Feedback:** {coaching.get('mi_feedback', '')}")
            lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Clinical Frameworks")
    lines.append("")
    lines.append("This report was generated using:")
    lines.append("- **C-SSRS** (Columbia Suicide Severity Rating Scale) — cssrs.columbia.edu")
    lines.append("- **SAMHSA Motivational Interviewing Guidelines**")
    lines.append("")
    lines.append("*All data is synthetic. No real caller data is used.*")
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by CrisisLens · {today}*")

    return "\n".join(lines)
